shadow = true;
inactive-opacity = 0.8;
no-fading-openclose = true;
vsync = true;
backend = "glx";
focus-exclude = [ "name *= 'rofi'", "window_type = 'dock'", "window_type = 'desktop'", "n:e:Notification","class_g = 'Xfwm4'", "class_g = 'Polybar'", "class_g ?= 'Cairo-dock'", "class_g ?= 'Xfce4-notifyd'", "class_g ?= 'Xfce4-power-manager'", "class_g ?= 'Notify-osd'", "_GTK_FRAME_EXTENTS@:c", "class_g = 'slop'" ];
