shadow = false;
shadow-radius = 13;
shadow-opacity = .8;
shadow-offset-x = -13;
shadow-offset-y = -13;
no-fading-openclose = true;
vsync = true;
backend = "glx";
rules = (
  { match = "focused"; shadow = true; },
  { match = "name = 'xfce4-session'"; shadow = false; },
  { match = "name = 'xfce4-panel'"; shadow = false; },
  { match = "name = 'Whisker Menu'"; shadow = false; }
)
