#!/bin/sh
set -e

cleanup() {
    exec 3>&-
	rm "$FIFO_UEBERZUG"
}

if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
	lf "$@"
else
	[ ! -d "$HOME/.cache/lf" ] && mkdir --parents "$HOME/.cache/lf"
	export FIFO_UEBERZUG="$HOME/.cache/lf/ueberzug-$$"
	mkfifo "$FIFO_UEBERZUG"
	ueberzug layer -s <"$FIFO_UEBERZUG" -p json &
	exec 3>"$FIFO_UEBERZUG"
	trap cleanup EXIT
  LF_ICONS=$(sed ~/.config/lf/icons \
    -e '/^[ \t]*#/d'       \
    -e '/^[ \t]*$/d'       \
    -e 's/[ \t]\+/=/g')
  LF_ICONS=${LF_ICONS//$'\n'/:}
  export LF_ICONS
  export LF_COLORS=".git/=01;97:.git*=97:*.gitignore=97:*Makefile=97:README.*=33:*.txt=37:*.jpeg=33:*.jpg=33:*.png=33:*.gif=33:*.tga=33:*.tif=33:*.tiff=33:*.svg=33:*.mp4=35:*.mkv=35:*.webm=35:*.avi=35:*.mp3=35:*.flac=35:*.wav=35:*.ogg=35:*.m4a=35:*.m4v=35:*.md=97:ln=01;36:di=1;94:tw=1;94:ow=1;94:st=1;94:ex=01;92:*.tar=31:*.tgz=31:*.arc=31:*.arj=31:*.taz=31:*.lha=31:*.lz4=31:*.lzh=31:*.lzma=31:*.tlz=31:*.txz=31:*.tzo=31:*.t7z=31:*.zip=31:*.z=31:*.dz=31:*.gz=31:*.lrz=31:*.lz=31:*.lzo=31:*.xz=31:*.zst=31:*.tzst=31:*.bz2=31:*.bz=31:*.tbz=31:*.tbz2=31:*.tz=31:*.deb=31:*.rpm=31:*.jar=31:*.war=31:*.ear=31:*.sar=31:*.rar=31:*.alz=31:*.ace=31:*.zoo=31:*.cpio=31:*.7z=31:*.rz=31:*.cab=31:*.wim=31:*.swm=31:*.dwm=31:*.esd=31:*.iso=31:"

	lf "$@" 3>&-
fi
